# Canonical geographic order for each game's locations.
# Matching uses substring: `canonical_key in location_string` (first match wins).
# More specific keys must come before less specific ones to avoid false matches
# (e.g. "Route 111 Desert" before "Route 111").

LOCATION_ORDER = {
    "emerald": [
        "Littleroot Town",
        "Route 101",
        "Route 102",
        "Petalburg Woods",
        "Route 104",
        "Rusturf Tunnel",
        "Granite Cave",
        "Route 110",
        "Route 117",
        "Route 111 Desert",   # must precede "Route 111"
        "Route 111",
        "Route 112",
        "Fiery Path",
        "Jagged Pass",
        "Lavaridge Town",
        "Route 113",
        "Meteor Falls",
        "Route 114",
        "Route 116",
        "Route 118",
        "Route 119",
        "Weather Institute",
        "Routes 119 / 120",   # Kecleon — must precede "Route 120"
        "Route 120",
        "Ancient Tomb",
        "Safari Zone",
        "Route 123",
        "Mt. Pyre",
        "Route 124",
        "Mossdeep City",
        "Shoal Cave",
        "Underwater",
        "Ever Grande City",
        "Island Cave",        # Regice (Route 105, Regi puzzle)
        "Desert Ruins",       # Regirock (Route 111, Regi puzzle)
        "Sky Pillar",
        "Artisan Cave",
        "Battle Frontier",
        "Roaming Hoenn",
        "Any ocean",
        "Breed",
        "Trade Clamperl",
        "Appears in empty party slot",
        "Event-only",
    ],

    "firered": [
        "Pallet Town",
        "Route 1 ",           # trailing space prevents matching Route 11/12/etc.
        "Route 22",
        "Viridian Forest",
        "Pewter Museum",
        "Mt. Moon",
        "Route 3 ",           # trailing space
        "Route 4 ",           # trailing space (also catches "Route 4 / 8 / 11")
        "Route 24",
        "Route 25",
        "Cerulean City",
        "Route 5",
        "Route 6",
        "Route 7",
        "Route 8",
        "Vermilion City",
        "Diglett's Cave",
        "Route 11",
        "Route 12",
        "Route 13",
        "Route 14",
        "Route 15",
        "Rock Tunnel",
        "Pokémon Tower",
        "Celadon",
        "Route 16",
        "Route 17",
        "Route 18",
        "Safari Zone",
        "Route 19",
        "Route 20",
        "Route 21",
        "Seafoam Islands",
        "Pokémon Mansion",
        "Saffron City",
        "Silph Co.",
        "Power Plant",
        "Route 2 ",           # Route 2 NPC trade — accessible post-badge
        "Cerulean Cave",
        # Sevii Islands in island order 1 → 7
        "Mt. Ember",
        "One Island",
        "Kindle Road",
        "Three Isle Path",
        "Bond Bridge",
        "Icefall Cave",
        "Five Isle Meadow",
        "Five Island",
        "Water Labyrinth",
        "Lost Cave",
        "Pattern Bush",
        "Six Island",
        "Tanoby Ruins",
        "Sevault Canyon",
        "Birth Island",
        # Non-geographic
        "Prof. Oak",
        "Any ocean",
        "Breed",
        "Trade",
        "Event-only",
    ],

    "leafgreen": [
        "Pallet Town",
        "Viridian Forest",
        "Mt. Moon",
        "Route 4 ",
        "Cerulean City",
        "Route 5",
        "Route 6",
        "Route 7",
        "Route 8",
        "Route 21",
        "Seafoam Islands",
        "Pokémon Mansion",
        "Cinnabar Island",
        "Saffron City",
        "Safari Zone",
        "Cerulean Cave",
        "Icefall Cave",
        "Five Isle Meadow",
        "Lost Cave",
        "Six Island",
        "Breed",
        "Event-only",
    ],

    "colosseum": [
        "Phenac City",
        "Pyrite Town",
        "Pyrite Building",
        "Agate Village",
        "The Under",
        "Realgam Tower",
        "Mt. Battle",
        "Cipher Lab",
        "Pokémon Colosseum",  # catch-all for any remaining colosseum entries
    ],

    "xd": [
        "Cipher Key Lair",
        "Citadark Isle",
        "Mt. Battle",
        "Pokémon XD",
    ],

    "ruby": [
        "Littleroot Town",
        "Route 101",
        "Route 102",
        "Petalburg Woods",
        "Route 104",
        "Granite Cave",
        "Route 110",
        "Route 111",
        "Route 112",
        "Route 113",
        "Route 114",
        "Meteor Falls",
        "Route 116",
        "Route 117",
        "Route 118",
        "Route 119",
        "Route 120",
        "Route 123",
        "Cave of Origin",
        "Sky Pillar",
    ],

    "sapphire": [
        "Littleroot Town",
        "Route 101",
        "Route 102",
        "Granite Cave",
        "Shoal Cave",
        "Route 117",
        "Route 118",
        "Route 119",
        "Cave of Origin",
        "Sky Pillar",
    ],

    # ── Gen 5 ────────────────────────────────────────────────
    "black":  [],
    "white":  [],
    "black2": [],
    "white2": [],
}
