"""Generate the OpenPokedex app icon: a Poké Ball.

Outputs:
  static/icon.png  — 256x256 PNG, used as the pywebview window icon.
  build/icon.ico   — multi-resolution .ico used by PyInstaller for the .exe.

Run once with `python scripts/make_icon.py`. The PNG should be committed.
The ICO is a build artifact and regenerated by the GitHub Actions workflow.
"""
import os
from PIL import Image, ImageDraw

SIZE = 256
OUT_PNG = os.path.join(os.path.dirname(__file__), "..", "static", "icon.png")
OUT_ICO = os.path.join(os.path.dirname(__file__), "..", "build", "icon.ico")


def draw_pokeball(size):
    img = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)

    pad = size * 0.06
    ball = (pad, pad, size - pad, size - pad)

    # Outer black ring + red top + white bottom.
    d.ellipse(ball, fill=(0, 0, 0, 255))
    inner_pad = pad + size * 0.025
    inner = (inner_pad, inner_pad, size - inner_pad, size - inner_pad)
    d.pieslice(inner, 180, 360, fill=(238, 28, 36, 255))  # red top
    d.pieslice(inner, 0, 180, fill=(255, 255, 255, 255))   # white bottom

    # Center horizontal black band.
    band_h = size * 0.10
    cy = size / 2
    d.rectangle((pad, cy - band_h / 2, size - pad, cy + band_h / 2), fill=(0, 0, 0, 255))

    # Center button: black outer, white inner.
    btn_r = size * 0.13
    d.ellipse((size/2 - btn_r, size/2 - btn_r, size/2 + btn_r, size/2 + btn_r), fill=(0, 0, 0, 255))
    btn_r2 = size * 0.085
    d.ellipse((size/2 - btn_r2, size/2 - btn_r2, size/2 + btn_r2, size/2 + btn_r2),
              fill=(255, 255, 255, 255))

    return img


def main():
    os.makedirs(os.path.dirname(OUT_PNG), exist_ok=True)
    os.makedirs(os.path.dirname(OUT_ICO), exist_ok=True)

    master = draw_pokeball(SIZE)
    master.save(OUT_PNG, "PNG")
    print(f"wrote {OUT_PNG}")

    # ICO with the resolutions Windows actually uses.
    sizes = [(16, 16), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)]
    master.save(OUT_ICO, format="ICO", sizes=sizes)
    print(f"wrote {OUT_ICO}")


if __name__ == "__main__":
    main()
